### PR TITLE
Fix build warnings

### PR DESCRIPTION
**Pull request by drott**
Fix a set of build warnings for signed/unsigned comparison
as well as unused variables.

### CODE REVIEW

**Review by cherusker — APPROVED** [review]
Nice ones, thanks! 😊

**Comment by drott** [comment]
Thanks for the review - @cherusker, do you have merge access here, could you merge it? Thanks.

**Comment by cherusker** [comment]
ah I thought you had the option to merge it yourself @drott, once it's approved but turns out I was wrong 🙊

**Comment by drott** [comment]
Thanks!

**Pull request merged**
