### PR TITLE
Activate FT_DEBUG_LOGGING for the driver.

### PR DESCRIPTION
**Pull request by lemzwerg**
It's useful to execute the driver with something like

  FT2_DEBUG="any: -vt"

to get timings and the affected modules.

### CODE REVIEW

**Comment by lemzwerg** [comment]
I've now fixed the four failures in the test suite (I wonder how why there weren't reports for them), so this is ready to merge.

**Comment by cherusker** [comment]
😃 sounds great! tiny qq (might be missing something in the diff on my phone); what changed in `ftoption.patch`? 🤔

**Comment by lemzwerg** [comment]
> sounds great! tiny qq (might be missing something in the diff on my phone);
> what changed in `ftoption.patch`?

Nothing.  I had some incorrect changes there that are no longer there with the latest commit.  However, the line numbers are updated.

**Comment by cherusker** [comment]
> > sounds great! tiny qq (might be missing something in the diff on my phone);
> > what changed in `ftoption.patch`?
> 
> Nothing. I had some incorrect changes there that are no longer there with the latest commit. However, the line numbers are updated.

Ahhh I see 😊 👍 ... would the patch still apply though? I'm not overly fussed but if there's no need to change it with this PR I think I'd rather leave it out for now and bump it when it's required. Let me know if you disagree with that and I'm happy to approve as is! 😊

**Comment by lemzwerg** [comment]
> I'm not overly fussed but if there's no need to change it with this PR
> I think I'd rather leave it out for now and bump it when it's required.

OK, reverted.

**Review by cherusker — APPROVED** [review]
omg sorry just came to think of this PR .... 😭 💛

**Pull request merged**
