### PR TITLE
Fix libpng build.

### PR DESCRIPTION
**Pull request by lemzwerg**

### CODE REVIEW

**Comment by bungeman** [comment]
I think we explicitly wanted the fully locally built and locally installed versions of these libraries to avoid issues where we need to know about the internal build processes like any `.libs` directory or something like that (and also since we need the installed headers anyway, since the local ones are sometimes incorrect or more or less impossible to use correctly; both libpng and zlib headers are basically impossible to use correctly until they are installed, especially with the symbol renaming being done here). In the install step I see the `ln -s libpng16.a libpng.a` happening, so I would assume that we can link against `libpng.a` directly. Was this not being created somewhere?

**Comment by lemzwerg** [comment]
AFAICS, the link to `libpng.a` is created during the installation step.  However, you were hard-coding the target directory as `.../usr/lib/...` for the library.  On my GNU/Linux box it is `.../usr/lib64/...`, thus linking fails.

Do you know how to fix this easily, this is, how to find out whether to use `lib` or `lib64` in the library path?

**Comment by bungeman** [comment]
Hmmm, I suppose this could be forced with `--libdir` (since these aren't actually going to be system installed, this process is kinda building up a custom distro full of packages built with sanitizers). It seems autotools uses `config.site` file which is found in conjunction with `CONFIG_SITE` which can set this sort of thing, but I wouldn't expect it to be used here since a prefix was set (it seems CentOS / Red Hat do this). I was thinking maybe we could use `pkg-config` but I think one would already need to know the name of the library directory to tell it to look at. Since this build file kinda wants to know exactly where to look for libs, maybe the build files should explicitly set the `libdir` (in an ideal world possibly even to something like `usr/lib-asan` or something like that, though that isn't needed right now).

**Comment by lemzwerg** [comment]
Using `--libdir` is an excellent idea!  Unfortunately, it fails.  Even if I say `--libdir=lib-asan` in `scripts/build/libpng.sh`, I get the following during the build of libpng:
```
/bin/sh ./libtool  --tag=CC   --mode=link ccache clang  \
  -fsanitize=address -fsanitize-address-use-after-scope  \
  -fsanitize=undefined   -g -O0   -DFT_DEBUG_LEVEL_TRACE \
  -DFT_DEBUG_LEVEL_ERROR -DFT_DEBUG_MEMORY  \
  -L/home/wl/git/freetype/freetype2-testing/external/zlib/usr/lib \    <===
  -o png-fix-itxt contrib/tools/png-fix-itxt.o  -lm -lz 
```
which later on causes errors like `undefined reference to crc32`.

Looks like an upstream bug...  Or am I doing something wrong?

**Comment by bungeman** [comment]
The line `-L/home/wl/git/freetype/freetype2-testing/external/zlib/usr/lib \    <===` is in reference to where to look for zlib, I think one would need to add a `--libdir` to the zlib build as well and edit the libpng `LDFLAGS` which state where to find it.

Locally a change like [mylib.txt](https://github.com/freetype/freetype2-testing/files/5654694/mylib.txt) seems to work to stick everything in a `mylib` directory and refer to it.

**Comment by lemzwerg** [comment]
It works.  Thanks a lot!  I've updated this pull request with a beautified version of your code.

**Review by bungeman — APPROVED** [review]

**Comment by lemzwerg** [comment]
What must I do now to be able to merge this into master?

**Review by bungeman — APPROVED** [review]

**Comment by bungeman** [comment]
I'm not sure what the various labels are supposed to mean, but apparently I don't have write permission so I can review but it doesn't mean much for submission. Added cherusker who I know does. Armin, can you poke about the settings and see why lemzwerg doesn't seem to have write permissions? He should probably be a member of https://github.com/orgs/freetype/people too.

**Comment by cherusker** [comment]
hi guys sorry for the delay; yeah @lemzwerg happy to review permissions on this repo! 😊 let's maybe quickly catch up on who you'd like to have which level of access + happy to expand that then! 😊 right now it would e.g. require an approve of you, me, nikolaus, nikhil or nicolas ("owners" of the `freetype` org) and only we could merge that; @bungeman, dominik + oliver are currently set on "triage" for this repo where I hoped that this would give enough access to make contributions once things are approved but it's clearly not enough 😞

**Review by cherusker — APPROVED** [review]
this approve should let you @lemzwerg merge this PR now

**Comment by lemzwerg** [comment]
Worked now, thanks!

**Pull request merged**
