### PR TITLE
Update .gitmodules to new FreeType repository

### PR DESCRIPTION
**Pull request by drott**

### CODE REVIEW

**Comment by drott** [comment]
This would be quite urgent to merge - it looks like the fuzzing has not been tracking commits since January.

**Review by cherusker — APPROVED** [review]
Oh oh! I would've thought that the new repository was mirrored back to Savannah but not a bad idea to point that to the new repo regardless 👍 Thanks for that commit!

**Comment by drott** [comment]
> Oh oh! 

That's what I thought. 

> I would've thought that the new repository was mirrored back to Savannah […]

It was for a while, but it stopped syncing in January.

Thanks for merging.

**Comment by cherusker** [comment]
> Thanks for merging.

Thanks for raising!

**Pull request merged**
